# compose.ci.yml - Configuration pour CI/CD (SANS bind mounts)
services:
  frontend:
    build:
      context: ./biblioflow-frontend
      dockerfile: Dockerfile
      target: production
    volumes:
      - frontend_node_modules_ci:/app/node_modules  # Seulement les volumes nécessaires
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./biblioflow-backend
      dockerfile: Dockerfile
      target: production
    volumes:
      - backend_node_modules_ci:/usr/src/app/node_modules  # Seulement les volumes nécessaires
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://biblioflow:biblioflow@postgres:5432/biblioflow
      - MONGODB_URL=mongodb://mongodb:27017/biblioflow
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  postgres:
    volumes:
      - postgres_data_ci:/var/lib/postgresql/data

  mongodb:
    volumes:
      - mongodb_data_ci:/data/db

  nginx:
    volumes:
      - nginx_logs_ci:/var/log/nginx

volumes:
  postgres_data_ci:
  mongodb_data_ci:
  frontend_node_modules_ci:
  backend_node_modules_ci:
  nginx_logs_ci: