# compose.ci.yml - Configuration pour CI/CD (SANS bind mounts)
services:
  frontend:
    build:
      context: ./biblioflow-frontend
      dockerfile: Dockerfile
      target: production
    volumes: []  # ← AJOUTER cette ligne !
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./biblioflow-backend
      dockerfile: Dockerfile
      target: production
    volumes: []  # ← AJOUTER cette ligne !
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://biblioflow:biblioflow@postgres:5432/biblioflow
      - MONGODB_URL=mongodb://mongodb:27017/biblioflow
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  postgres:
    volumes:
      - postgres_data_ci:/var/lib/postgresql/data

  mongodb:
    volumes:
      - mongodb_data_ci:/data/db

  nginx:
    volumes: []  # ← AJOUTER cette ligne !
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

volumes:
  postgres_data_ci:
  mongodb_data_ci: