services:
  frontend:
    build:
      context: ./biblioflow-frontend
      dockerfile: Dockerfile
      target: dev
    container_name: jenkins-test-frontend
    volumes:
      - ./biblioflow-frontend:/usr/src/app
      - jenkins_test_frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "4201:4200"
    environment:
      - NODE_ENV=test
      - CI=true
      - CHROME_FLAGS=--no-sandbox --disable-dev-shm-usage
    networks:
      - jenkins_test_frontend